version: 8
scan:
  exclude_dirs:
  - .git
  - .pytest_cache
  - __pycache__
  - secrets
display:
  show_whitespace: false
  hide_mapping_order: false
  mute_non_focused: false
patterns: []
paths:
  project: ../../devops/deployment-configurations/eids
  source: dev
  target: test
